### ISSUE TITLE
Conflict on test_api version between flutter_test & dart-lang/test

### ISSUE THREAD

**Issue by PrasannaGnanaraj** [dart-lang/test#1247]
Im unable to add `test` as a dependency to my flutter project 

```
D:\foo>flutter pub get
Because every version of flutter_test from sdk depends on test_api 0.2.15 and test 1.14.5 depends on test_api 0.2.16, flutter_test from sdk is incompatible with test 1.14.5.
And because no versions of test match >1.14.5 <2.0.0, flutter_test from sdk is incompatible with test ^1.14.5.
So, because foo depends on both test ^1.14.5 and flutter_test any from sdk, version solving failed.
Running "flutter pub get" in foo...
pub get failed (1; So, because foo depends on both test ^1.14.5 and flutter_test any from sdk, version solving failed.)
```
D:\foo>cat pubspec.yaml

```
name: foo
description: A new Flutter project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dotenv: ^2.0.0
  fixnum: ^0.10.11
  protobuf: ^1.0.1
  grpc: ^2.1.3
  async: ^2.2.0
  postgres: ^1.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  faker: ^1.2.1
  flutter:
    sdk: flutter
  flutter_local_notifications:

dev_dependencies:
  test: ^1.14.5
  flutter_test:
    sdk: flutter

```
> flutter --version

```
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (11 days ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2
```

Appriciate any help you could offer

Update: 
Probably due to https://github.com/dart-lang/test/pull/1246
