### ISSUE TITLE
Version resolution failure with latest release (1.15.3)

### ISSUE THREAD

**Issue by Darrekt** [dart-lang/test#1315]
Hey everyone, I've found the following issue where it seems to clash with the in-built flutter testing library, with the following reproducible steps:

with the following `pubspec.yaml`:
```
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_redux: ^0.6.0
  flutter_circular_slider: ^2.5.0 
  animations: ^1.1.1
  test: ^1.15.3



dev_dependencies:
  flutter_test:
    sdk: flutter
```

The following error occurs in terminal (my flutter app is named Rise):
```bash
Because every version of flutter_test from sdk depends on test_api 0.2.17 and test >=1.15.3 <1.16.0-nullsafety depends on test_api 0.2.18, flutter_test from sdk is incompatible with test >=1.15.3 <1.16.0-nullsafety.

And because test >=1.16.0-nullsafety requires SDK version >=2.10.0-0 <2.10.0, flutter_test from sdk is incompatible with test >=1.15.3.

So, because Rise depends on both test ^1.15.3 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because Rise depends on both test ^1.15.3 and flutter_test any from sdk, version solving failed.)
exit code 1
```
The error does not occur if I change the line to `test: ^1.15.2`, so I thought this might be an issue with the latest version that needs to be brought to someone's attention. Since dart and flutter are so closely coupled, wouldn't we want their latest releases to be compatible by default?

Sorry if this turns out to be a really trivial issue, I just thought it might be helpful or important for someone to know. Feel free to close it if it can be solved trivially otherwise!
