### ISSUE TITLE
Non opted in file in NNBD prerelease

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/test#1392]
version: 1.16.0-nullsafety.12

```
The package resolution is not fully migrated to null-safety.

package:test/src/runner/node/platform.dart is opting out of null safety:
  ╷
5 │ // @dart=2.7
  │ ^^^^^^^^^^^^
  ╵
```

pubspec.yaml of use:

```yaml
name: sqlite3
version: 0.0.1
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  ffi: ^0.2.0-nullsafety.1
dev_dependencies:
  test: ^1.16.0-nullsafety.12
```
