### ISSUE TITLE
Allow the latest analyzer package (0.42.0-nullsafety)

### ISSUE THREAD

**Issue by lzoran** [dart-lang/test#1428]
Having null-safety versions of the `analyzer` and `test` packages within the same project creates dependency versions conflict.

The `pubspec.yaml` file of the project:
```
environment:
  sdk: '>=2.12.0-0 <3.0.0'

...

dependencies:
  analyzer: ^0.42.0-nullsafety
  ...

dev_dependencies:
  test: ^1.16.0-nullsafety
```

Error message:
> 
> Because test >=1.16.0-nullsafety.7 <1.16.0-nullsafety.10 depends on analyzer >=0.36.0 <0.41.0 and test >=1.16.0-nullsafety <1.16.0-nullsafety.7 requires SDK version >=2.10.0-0
>   <2.11.0, test >=1.16.0-nullsafety <1.16.0-nullsafety.10 requires analyzer >=0.36.0 <0.41.0.
> And because test >=1.16.0-nullsafety.10 depends on analyzer >=0.36.0 <0.42.0, test >=1.16.0-nullsafety requires analyzer >=0.36.0 <0.42.0.
> So, because my_package depends on both analyzer ^0.42.0-nullsafety and test ^1.16.0-nullsafety, version solving failed.
