### ISSUE TITLE
Support for tags

### ISSUE THREAD

**Issue by zoechi** [dart-lang/test#16]
During development I won't care about a lot of tests, especially integration tests (which are often slow(er)). By using tags I could declare sets of unit tests I care about and are likely to break because of what I'm working on.
This would make it more convenient to run tests frequently.
Running all tests is more appropriate for checkin hooks and CI.

This feature could be combined with #6, #7, #14 

Examples:
- run only server tests (tag: `server`)
- run only fast server tests (tags: `server,unittest`) (as don't run `integration` tests)
- run all firefox tests (tags: `firefox`)
- could be combined with #14 (tags: `-skip`) (exclude `skip`)
- run tests for a specific feature (tags: `authentication`)

It should be supported to add tags at group and test level, where tags on a group apply also to tests within that group.

I just found an example where this is already done http://olivinelabs.com/busted/.

**Comment by nex3** [comment]
I did some thinking about this, and here's how I envision it working:

Tags are defined in roughly the same manner as other metadata. For example,

```dart
@Tag("awesome")

void main() {
  group("a neat group", () {
    test("a fun test", () {
      // ...
    }, tag: ["fun", "cool"]);
  }, tag: "neat");
}
```

Alternately, we could say that `tag:` always takes a string and that the string is comma-separated for multiple tags. Tags can be arbitrary strings, but to catch typos, they must be declared in the config file (#46):

```yaml
tags:
  awesome:
  fun:
  cool:
  neat:
```

Tags can be used from the command-line with the `--exclude` and `--include` (`--only`?) flags, which specify which tags not to run or to run exclusively, respectively.

Tags can also have metadata associated with them in the configuration file. This metadata applies to all tests with that tag. For example:

```yaml
tags:
  slow: {timeout: 2x}
  ie: {test_on: windows}
  git:
    on_platform:
      windows: {timeout: 2x}
```

Tags can also be configured differently for different presets (#83). For example:

```yaml
presets:
  travis:
    tags: {ie: {skip: true}}
```
