### ISSUE TITLE
Test 1.20.1 incompatible with Flutter 2.10

### ISSUE THREAD

**Issue by DenisGL** [dart-lang/test#1666]
After adding test 1.20.1 support in pubspec.yaml :

```
...
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0
  test: ^1.20.1
...
```

in the Flutter example (generated with `flutter create example_app`), doing a `flutter pub get` displays this message:

```
Running "flutter pub get" in example_app...                        
Because every version of flutter_test from sdk depends on test_api 0.4.8 and test >=1.20.0 depends on test_api 0.4.9, flutter_test from sdk is incompatible with test >=1.20.0.
So, because example_app depends on both test ^1.20.1 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because example_app depends on both test ^1.20.1 and flutter_test from sdk, version solving failed.)

```
