### ISSUE TITLE
Incompatibility of ^1.20.x versions with integration_test package

### ISSUE THREAD

**Issue by lucavenir** [dart-lang/test#1682]
Hi there,

this is my first issue in this repo, so I hope I'm doing it right.
I know this is a `dart` - related package, but when configuring my `pubspec.yaml` inside a new Flutter app with the following dev dependencies:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.20.2
```

I get the following output:
```
[my_project] flutter pub get
Running "flutter pub get" in my_project...                    
Because every version of integration_test from sdk depends on test_api 0.4.8 and test >=1.20.0 depends on test_api 0.4.9, integration_test from sdk is incompatible with test >=1.20.0.
So, because my_project depends on both integration_test from sdk and test ^1.20.0, version solving failed.
pub get failed (1; So, because my_project depends on both integration_test from sdk and test ^1.20.0, version solving failed.)
exit code 1
```

I guess the message is pretty self-explaining, but since I saw no issues about this on this repo, I thought I'd help by posting it here; I guess tracking this compatibility may be helpful.

Note how this is not crucial to me, as I'm keeping my `test` package in my project at `^1.19.5`, at the moment.

Finally, consider that I'm being redirected to using this package from [Flutter's testing tutorial](https://codelabs.developers.google.com/codelabs/flutter-app-testing).

**Comment by jakemac53** [comment]
This is because flutter pins their `test_api` version. You will not be able to use the latest version of `test` until flutter updates (you may be able to switch to a dev channel to get the update faster).

The fix is to not require the latest version in your package, something like the following:

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.0.0
```

Unless you require a feature from a specific version, this lax constraint is going to be the most flexible and least prone to dependency lock.
