### ISSUE TITLE
Exit code of 0 after a failed test

### ISSUE THREAD

**Issue by cpswan** [dart-lang/test#2248]
___Describe the bug in detail.___

A test (or tests) fail, but the exit code for the `dart test` process is 0.

@gkc first noticed this on a [GitHub Action run](https://github.com/atsign-foundation/at_libraries/actions/runs/9191223708/job/25277175158). (Full logs at [logs_24055523517.zip](https://github.com/user-attachments/files/16057145/logs_24055523517.zip).)

> test/enrollment_test.dart: A test to verify send enroll request, deny enrollment and auth by enrollmentId should fail (failed)

![image](https://github.com/dart-lang/test/assets/478926/02937a3d-5ad0-414d-93c8-ba4934915011)

However the job still passed.

This was initially thought to be an issue with GitHub Actions, and @gkc opened https://github.com/atsign-foundation/at_libraries/issues/586 but the behavior has since been replicated locally, so it looks like it's a `dart test` problem rather than a GitHub Actions problem.

___Include the specific command you ran and any relevant details about the
environment, including operating system, Dart SDK version, and the version of
`package:test` you are using.___

`dart test --concurrency=1`

`Dart SDK version: 3.4.1 (stable) (Tue May 21 15:46:25 2024 +0000) on "linux_x64"`

```
+ test 1.25.7
+ test_api 0.7.2
+ test_core 0.6.4
```

___Whenever possible, include a full reproduction example that we can run to
observe the problem.___

This will need Docker Compose.

```sh
 git clone https://github.com/atsign-foundation/at_libraries.git
 cd at_libraries/
 git checkout tests-testing
 cd tests/at_onboarding_cli_functional_tests/
 echo "127.0.0.1    vip.ve.atsign.zone" | sudo tee -a /etc/hosts
 dart pub get
 sudo docker compose up -d
 dart run check_docker_readiness.dart
 dart test --concurrency=1
 echo $?
```

@mit-mit this is the thing I mentioned to you last week at I/O Connect, so this is the GitHub issue you asked me to open.

**Comment by jakemac53** [comment]
Can you create a reproduction case that doesn't require docker?

**Comment by cpswan** [comment]
@jakemac53 i don't think we can create a replication for this without docker in a reasonable time frame.

I also suspect that at the heart of this is a bunch of async stuff leading to a race condition, and the docker based services provide a substrate for that to happen.

**Comment by jakemac53** [comment]
@cpswan can you provide more of the error logs?

**Comment by jakemac53** [comment]
Fwiw, I have validated that late async errors in `setUp`, `tearDown`, and regular tests all do set the exit code appropriately.

**Comment by cpswan** [comment]
@jacob314 I already attached the full log archive from the original GitHub Actions run where we first spotted this (and the specific log within that archive is 2_functional_tests_at_onboarding_cli (at_onboarding_cli_functional_tests).txt.

What other logs can I get for you?

**Comment by jakemac53** [comment]
@cpswan I don't see anything obvious, I created a [branch](https://github.com/dart-lang/test/tree/add-prints) of test_core with some extra print statements just to get an idea of what state the runner thinks it is in. If you can run using that link the result that would help to get a start here, you should be able to use it by adding something like this to your pubspec:

```yaml
dependency_overrides:
  test_api:
    git:
      url: https://github.com/dart-lang/test/
      ref: add-prints
      path: pkgs/test_api
  test_core:
    git:
      url: https://github.com/dart-lang/test/
      ref: add-prints
      path: pkgs/test_core
  test:
    git:
      url: https://github.com/dart-lang/test/
      ref: add-prints
      path: pkgs/test
```
