### ISSUE TITLE
malformed type: line 131: type 'QueueList<LiveTest>' is not loaded

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/test#287]
I've been getting a strange error when upgrading dependencies for the `atlassian_connect_*` projects.

This is what I get

```
blah:atlassian_connect_shelf aholmgren$ pub run test
'package:test/src/runner/engine.dart': malformed type: line 131: type 'QueueList<LiveTest>' is not loaded
  final _active = new QueueList < LiveTest >();
                      ^
type error.
dart:core                                _TypeError._throwNew
package:test/src/runner/engine.dart 131  Engine.Engine
package:test/src/executable.dart 132     main.<async>

This is an unexpected error. Please file an issue at http://github.com/dart-lang/test
with the stack trace and instructions for reproducing the error.
```

The strange thing is that I have hit this on each project (3 of them) so far. 

* Running `pub cache repair` on the first project fixed that project when I run it from the command line
* But running the test in the latest intellij still gets the same problem. Odd cause i thought it just rang `pub run test` these days

So then I moved on to the second project

* same problem again
* deleting all the local .pub, packages, .packages folders did not fix it
* but running `pub cache repair` did, but not within intellij again.

Same thing on the third package

The pubspec.yaml for the first project is

```
author: Anders Holmgren <aholmgren@atlassian.com>
description: Atlassian Connect extensions for Json Web Token
homepage: https://bitbucket.org/aholmgren/ac-dart
name: atlassian_connect_jwt
version: 0.2.3
dependencies: 
  collection: '>=0.9.1 <0.10.0'
  logging: '>=0.9.1+1 <0.10.0'
  path: '>=1.0.0 <2.0.0'
  quiver: '>=0.18.0 <0.22.0'
  dart_jwt: 
    path: /Users/aholmgren/Projects/dart/connect/jefe-acdart/new-acdart_root/dart_jwt
dependency_overrides: 
dev_dependencies: 
  test: '^0.12.0'
environment: 
  sdk: '>=1.3.0 <2.0.0'

```

So I realise I haven't given you enough info to solve this problem, but am hoping you have some suggestions for how to debug this
