### ISSUE TITLE
Multiple files in pub serve transformer

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/test#387]
I have test setup I want to run in the browser. It consists of a lot of test files and I use reflectable.

So I first I added all individual tests as entry points (no wildcards https://github.com/dart-lang/reflectable/issues/67) and had a pubspec like this:
```yaml
transformers:
- reflectable:
    entry_points:
      - test/first_test.dart
[...]
      - test/last_test.dart
- test/pub_serve:
    $include: test/**_test.dart
```

However, like this, the test script compiles every single test individually and it takes a very long time. So I created a separate file in `test/` that imports all other tests and runs them (like you used to do with unittest before). I could not call the file `*_test.dart` because it would make all tests run twice when I do `pub run test`. So I called it `test/all_tests_web.dart`. This became the pubspec.yaml:
```yaml
transformers:
- reflectable:
    entry_points:
      - test/all_test_web.dart
- test/pub_serve:
    $include:
      - test/**_test.dart
      - test/all_tests_web.dart
```

However, I always got this exception (I did the `--pub-test=8081` thing right):
```                                                     
  Failed to load "test/all_test_web.dart":
  Error getting http://localhost:8081/all_test_web.dart.browser_test.dart.js.map: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
```
It seems like `$include` can only take one argument.

Then, I saw that the pub test documentation adds `{.*,}` to their `pub_serve` transformer include. So I tried this:
```yaml
transformers:
- reflectable:
    entry_points:
      - test/all_test_web.dart
- test/pub_serve:
    $include:
      - test/**_test{.*,}.dart
      - test/all_tests_web{.*,}.dart
```
But I keep getting the same error:
```                                                      
  Failed to load "test/all_test_web.dart":
  Error getting http://localhost:8081/all_test_web.dart.browser_test.dart.js.map: 404 Not Found
  Make sure "pub serve" is serving the test/ directory.
```

The whole testing setup when using barback is way too complicated. It should either be well explained in the documentation or it should be made simpler.
