### ISSUE TITLE
Add configurable platform support

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/test#391]
Chromium and Chrome should have similar run properties. However Chromium is open-source, while Chrome is branded. This makes Chromium more widely available on Linux systems and the preferred choice of many Linux users.

Since they would probably only differ in the name of the command, it's easy to add Chromium support as a separate platform, but alternatively, the `chrome` platform could just use `google-chrome` or `chromium`, whichever is available. (I assume something similar should already happen in order to support `google-chrome-beta`.)

**Comment by nex3** [comment]
I'm going to retarget this issue to refer to general support for configuring platforms. This is blocked on #46, since that's where the configuration will live.

I envision the ability to define new platforms that are small configurations of existing ones, like so:

```yaml
platforms:
  chromium:
    type: chrome
    name: Chromium
    executable: chromium
```

The "type" is an existing platform whose spawning logic can be re-used. The name is an optional human-readable name for that platform, and the executable is the executable name.

In practice, finding the executable will likely be a little more complicated than that, because different operating systems have different locations and executable path conventions. We'd probably want to support something like this:

```yaml
platforms:
  chromium:
    type: chrome
    name: Chromium
    executable:
      linux: chromium
      mac_os: /Applications/Chromium.app/Contents/MacOS/Chromium
      windows: Chromium\Application\chrome.exe
```

Absolute paths would be resolved absolutely, executable names would use the executable path, and for Windows in particular relative paths would check against `LOCALAPPDATA`, `PROGRAMFILES`, and `PROGRAMFILES(X64)`.

You'd also be able to use this to override the executable locations of existing platforms:

```yaml
platforms:
  dartium:
    executable:
      linux: dartium
      mac_os: /Applications/Dartium.app/Contents/MacOS/Chromium
      windows: Dartium\Application\chrome.exe
```

**Comment by stevenroose** [comment]
That sounds awesome!

**Comment by nex3** [comment]
Another thing I should mention: derived platforms would inherit the platform selectors of their parents, so `@TestOn("chrome")` would also allow a test to run on Chromium. They would also introduce their own platform selector variable, so `@TestOn("chromium")` would work as well.

**Comment by nex3** [comment]
Initial configuration file support has landed, so this is no longer blocked.

**Comment by StepFischer** [comment]
Is the topic of configurable platforms still in the work or is it abandoned?

**Comment by nex3** [comment]
This is definitely still something we plan to do (which is why this issue is still open :wink:).

**Comment by nex3** [comment]
I've started work on this, and I think the config format should be adjusted somewhat from the examples I wrote up before. For one thing, the field name `platforms` is [already in use](https://github.com/dart-lang/test/blob/master/doc/configuration.md#platforms), but there are a couple other goals I want to meet:

* The distinction between configuring an existing platform and defining a new platform via extension should be explicit. The former should be allowed in the global config, but the latter should not; we only want people to write `testOn: "chromium"` if Chromium is a defined platform within their package.

* Configuration should be forwards-compatible with platform plugins (#99), which probably means having a mapping that we can pass as-is to the plugin along with the new `TestPlatform`.

With that in mind, I think we should define configuration like this:

```yaml
# Overrides existing platforms. Runner configuration, allowed in the global or
# local file.
override_platforms:
  # Platform names must match existing platforms. This is validated after
  # plugins are loaded, so that plugin-defined platforms can be overridden.
  chrome:
    # "settings" is the only key here, to match define_platforms and to give us
    # the flexibility to add new fields without backward-compatibiliy issues.
    settings:
      # The contents of "settings" is passed as a YamlMap to the PlatformPlugin.
      executable: chromium

# Defines a new platform in terms of an existing one. Runner configuration,
# allowed only in the local file.
define_platforms:
  # Any (optionally hyphenated) Dart identifier is allowed.
  chromium:
    # "name", "extends", and "settings" are all required.
    name: Chromium

    # Only built-in and plugin platforms may be extended. That is, you can't
    # create another platform that extends chromium. This isn't strictly
    # necessary, but I don't see a good reason to allow multiple levels of
    # nesting.
    extends: chrome

    settings:
      # As above, this is passed directly to the PlatformPlugin.
      executable: chromium
```

Platform plugins that want to allow per-platform customization can then implement a `CustomizablePlatform` interface:

```dart
abstract class CustomizablePlatform {
  /// Defines user-provided [settings] for [platform].
  ///
  /// The [platform] is a platform this plugin was declared to accept when
  /// registered with [Loader.registerPlatformPlugin], or a platform whose
  /// [TestPlatform.parent] is one of those platforms. Subclasses should record
  /// the settings to use when [PlatformPlugin.loadChannel] or
  /// [PlatformPlugin.load] is called with the given [platform]. It's guaranteed
  /// to be called before either `load` method.
  ///
  /// If a [platform] has user-provided settings *and* extensions that have
  /// their own settings, this is guaranteed to be called with the parent
  /// platform before it's called with the child. It's the plugin's
  /// responsibility to make sure that the child's settings respect and override
  /// the parent's.
  ///
  /// Subclasses should throw [SourceSpanFormatException]s if [settings]
  /// contains invalid configuration.
  void customizePlatform(TestPlatform platform, YamlMap settings);
}
```

(Note that we could probably provide a better API if we had stateful mixins, but that's not likely to happen in time.)

@grouma What do you think of the configuration format and plugin API here?
