### ISSUE TITLE
Configuration unions

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#403]
We should support a `union` operator in the configuration file:

```yaml
preset:
  browser:
    union:
      - platforms: [chrome, content-shell]
      - include_tags: [browser]
```

It would run multiple more-or-less separate test runs with different configuration, but within the same process and using the standard test runner parallelization and unified reporter.

We'd have to define what configuration would be allowed in a union. All test configuration would be allowed, but some runner configuration (such as `concurrency` or `reporter`) wouldn't make sense. We'd probably want to define a separate category, "suite configuration", that includes the subset of what is now runner configuration that involves selecting or configuring entire test suites.
