### ISSUE TITLE
malformed type: line 95 pos 36: type 'DelegatingSink' is not loaded

### ISSUE THREAD

**Issue by scheglov** [dart-lang/test#438]
```
name: package_config
version: 0.1.4
description: Support for working with Package Resolution config files.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/package_config

environment:
  sdk: '>=1.11.0-dev.0.0 <2.0.0'

dependencies:
  charcode: ^1.1.0
  path: ^1.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
```

```
scheglov@scheglov-macbookpro3:~/dart/package_config (master)$ pub upgrade
Resolving dependencies... (3.3s)
  analyzer 0.26.4 (0.27.3 available)
  args 0.13.4+2
  async 1.11.0
  barback 0.15.2+8
  charcode 1.1.0
  collection 1.8.0
  convert 1.1.1 (2.0.0 available)
  crypto 0.9.2+1 (2.0.1 available)
  csslib 0.13.2
  glob 1.1.2
  html 0.12.2+2 (0.13.0 available)
  http_multi_server 1.3.2 (2.0.1 available)
  http_parser 0.0.2+8 (3.0.1 available)
  logging 0.11.3
  matcher 0.12.0+2
  mime 0.9.3
  path 1.3.9
  plugin 0.1.0 (0.2.0 available)
  pool 1.2.4
  pub_semver 1.2.4
  shelf 0.6.3 (0.6.5+2 available)
  shelf_static 0.2.3+4
  shelf_web_socket 0.0.1+5 (0.2.1 available)
  source_map_stack_trace 1.0.4
  source_maps 0.10.1+1
  source_span 1.2.2
  stack_trace 1.6.5
  string_scanner 0.1.5
  test 0.12.3+9 (0.12.13+4 available)
  typed_data 1.1.3
  utf 0.9.0+3
  watcher 0.9.7+2
  yaml 2.1.9
No dependencies changed.
scheglov@scheglov-macbookpro3:~/dart/package_config (master)$ dart test/all.dart
Unhandled exception:
'package:test/src/runner/engine.dart': malformed type: line 95 pos 36: type 'DelegatingSink' is not loaded
  Sink<Suite> get suiteSink => new DelegatingSink(_suiteController.sink);
```
