### ISSUE TITLE
"on_plaftform" and "presets" in configuration file seems not working together

### ISSUE THREAD

**Issue by yunjia** [dart-lang/test#461]
In the attached project [test-case.zip](https://github.com/dart-lang/test/files/460614/test-case.zip), the purpose is quite simple: 

1. To skip specific tagged tests when the tests is running on dart2js compiled browsers (but not on browsers with dart vm)
2. If passing `--preset blockers`, then should only run those tagged tests on dart2js compiled browsers

However, the result shows, the first requirement is working as expected, but the second one just runs no tests, even test that has no tag is also not run.

This is the output for two cases:
```
> pub run test
00:00 +0: [VM] test/simple_test.dart: package:test test that can't be run on js platform
00:00 +1: [Firefox] compiling test/simple_test.dart
00:00 +1: [VM] test/simple_test.dart: package:test normal test
00:00 +2: [Firefox] compiling test/simple_test.dart
00:00 +2: [Dartium Content Shell] test/simple_test.dart: package:test test that can't be run on js platform
00:00 +3: [Firefox] compiling test/simple_test.dart
00:00 +3: [Dartium Content Shell] test/simple_test.dart: package:test normal test
00:00 +4: [Firefox] compiling test/simple_test.dart
00:11 +4: [Firefox] test/simple_test.dart: package:test test that can't be run on js platform
  Skip: Dart2js blocking...
00:11 +4 ~1: [Firefox] test/simple_test.dart: package:test normal test
00:11 +5 ~1: All tests passed!
```
```
> pub run test -P blockers
No tests ran.
```

It may also because of my misunderstanding of `on_platform` usage. What I understand is that this field applies to tests, and if I put this field under tags, then that means it will only apply the setting for those tagged tests.

The configuration file dart_test.yaml is:
```
tags:
  blocker-web:
    on_platform:
      js:
        skip: 'Dart2js blocking...'
        presets: {blockers: {skip: false}}
reporter: expanded
platforms: [vm, firefox, content-shell]
presets:
  blockers:
    include_tags: blocker-web
```

And the test file is:
```
import 'package:test/test.dart';

main() {
  group("package:test", () {
    test("test that can't be run on js platform", () {
      expect(true, true);
    }, tags: ['blocker-web']);

    test("normal test", () {
      expect(true, true);
    });
  });
}
```
