### ISSUE TITLE
Share dart_test.yaml configuration across packages

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/test#723]
AngularDart (https://github.com/dart-lang/angular) uses a mono repository, which means we have several packages in this single repository with a shared set of analysis settings, and we manually try to keep dependencies in sync as well.

I'm working on using `dart_test.yaml` instead of passing duplicate flags across `pub run test` invocations. For example, I'd like to define the following presets/tags and share them across multiple packages:

```yaml
presets:
  # Only run tests that need to run within the browser.
  # * ... make the stack traces nicer.
  # * ... all tests in the browser likely need code generation.
  # * ... we currently only run these tests on chrome (today).
  browser:
    js_trace: true
    include_tags: codegen
    platform: chrome

  # Only run tests that need to run within the standalone VM.
  compiler:
    platform: vm

  # When running on travis:
  # * ... skip tests that don't work in this environment.
  # * ... increase timeouts (tests run slower here).
  # * ... do not use concurrency (we run out of resources).
  travis:
    exclude_tags: skip_on_travis
    timeout: 1.5x
    concurrency: 1

tags:
  # Tests that require code generation to be executed.
  #
  # * ... it's expected that these are manually tagged by the author.
  # * ... pass `--precompiled build` to `pub run test`.
  codegen:
    precompiled: build

  # Tests that are expected to fail on travis. These should be kept tightly
  # curated with tracking bugs, and are used to temporarily get our build
  # status to "green".
  skip_on_travis:
```

The only option I see today is writing a script to keep the following in sync:

* pkg_a/dart_test.yaml
* pkg_b/dart_test.yaml
* pkg_c/dart_test.yaml

The simplest solution I can think of is add a `--config` attribute to specify the path for `dart_test.yaml`. It could even default to current path logic if not specified. If added, I would use it like this:

```sh
$ pub run test --config ../dart_test_common.yaml -P compiler
```

Another alternative would be able to include and merge configuration files:

```yaml
include: ../dart_test_common.yaml
```

In my opinion, `--config` looks easier and would be more bullet-proof (don't have to deal with how to merge files/keys, for example), but I'm open to discussing both and any other options.
