### ISSUE TITLE
Trouble running Chrome in headless

### ISSUE THREAD

**Issue by Stargator** [dart-lang/test#751]
I've updated to 0.12.30 so I could migrate from using Dartium to running the tests in headless Chrome.

But the tests fail to run in with Chrome as the platform versus passing when dartium is the platform set.

I'm on a MacOS 10.12.6. And I am looking for feedback on whether my tests are not compatible with running in Chrome or if there's some other larger issue.

Overall, I am just not 100% certain I understand how to run my tests in headless Chrome.

When using package 0.12.29+1, I ran the tests in Chrome to see if they would pass then.

I'm using https://github.com/Stargator/dart_toh.git as my playground to test out the feature

After running pub run angular_test, I get the following 

```
The pub serve output is at /var/folders/57/6wq090815bb1x_vldxxk5yl40000gn/T/angular_test_pub_serve_output.log.
Run with --verbose to get this output in the console instead.
pub serve test --port=0
Pub "serve" started on http://localhost:62870
Finished compilation. Running tests...
pub run test --pub-serve=62870
00:00 +0: compiling test/all_test.dart
00:00 +0: test/app_test.dart: (suite)
Skip: AppComponent tests need bootstrap equivalent for the Router init
00:00 +0 ~1: compiling test/all_test.dart
"pub serve" is compiling test/all_test.dart...
Bad state: Should only get this output once.
package:angular_test/src/bin/runner.dart 62  run.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                   _Completer.completeError
package:angular_test/src/bin/runner.dart 74  run.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                   new Future.microtask
package:angular_test/src/bin/runner.dart 50  run.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                   Stream.forEach
package:angular_test/src/bin/runner.dart 50  run.<fn>
===== asynchronous gap ===========================
dart:async                                   _asyncThenWrapperHelper
package:angular_test/src/bin/runner.dart 44  run.<fn>
package:stack_trace                          Chain.capture
package:angular_test/src/bin/runner.dart 44  run
Shutting down...
`pub serve` was not terminated
00:30 +0 ~1 -1: compiling test/all_test.dart [E]
Failed to load "test/all_test.dart":
Error getting http://localhost:62870/all_test.dart.browser_test.dart.js.map: Connection closed before full header was received, uri = http://localhost:62870/all_test.dart.browser_test.dart.js.map
Make sure "pub serve" is running.
00:30 +0 ~1 -1: Some tests failed.
```

The dart_test.yaml file with changes I made so Chrome is the platform:

```yaml
# Test Configuration

# This is a browser-only package, so test on content shell by default.
platforms: [chrome]

# Determines that platform our tests will run on
test_on: "browser || vm" # Essentially all browsers and command line on Windows, Mac, and Linux

# This boolean field controls whether or not stack traces are chained. Disabling stack trace chaining will improve
# performance for heavily asynchronous code at the cost of debuggability.
chain_stack_traces: false

# This package's tests are fine. The default timeout.
timeout: "none"

# This boolean field controls whether or not stack traces caused by errors are trimmed to remove internal stack frames.
# This includes frames from the Dart core libraries, the stack_trace package, and the test package itself.
# It defaults to false.
verbose_trace: true

# This boolean field controls whether or not stack traces caused by errors that occur while running Dart compiled to JS
# are converted back to Dart style. This conversion uses the source map generated by dart2js to approximate the original
# Dart line, column, and in some cases member name for each stack frame. It defaults to false.
js_trace: false

# This field controls whether or not tests are skipped. It's usually applied to specific tags rather than used at the top level. Like the skip parameter for test(), it can either be a boolean indicating whether the tests are skipped or a string indicating the reason they're skipped.
tags:
  # Tests that are run with the Ahead of Time (AOT) compiler (ie: All AngularDart tests)
  aot:

  # Tag for any tests that need a browser
  browser:

  # Integration tests are fine, so use default timeout again.
  integration: {timeout: 1x}

  # Sanity tests are quick and verify that nothing is obviously wrong. Declaring
  # the tag allows us to tag tests with it without getting warnings.
  sanity:
    retry: 2 # Determines number of retries for a test

  ie:
    skip: "IE is not officially supported"

# Runner Configuration

reporter: expanded

# This field applies configuration when specific operating systems are being used.
on_os:
  windows:

  mac-os:

  linux:

# Indicates the filename pattern that the test runner uses to find test files in directories
# It defaults to "*_test.dart"
filename: "*_test.dart"

# Paths the Test Runner will find test files
# It defaults to test/
paths:
- test/
```
