### ISSUE TITLE
Support for test presets

### ISSUE THREAD

**Issue by nex3** [dart-lang/test#83]
Once there's a configuration file (#46), one particularly useful thing to do with it will be define test "presets". These would basically be named collections of options and defaults for the test runner that could easily be run by hand or by a test runner. For example:

```yaml
presets:
  travis:
    platforms: [vm, chrome, content_shell]
    timeout: 2x
```

This could then be invoked via `--preset travis` or `-P travis` to easily use that set of options.
