### ISSUE TITLE
test with lib ressource

### ISSUE THREAD

**Issue by JeromePuttemans** [dart-lang/test#984]
Hello, 

For my tests I need to get some ressource located in the lib folder as this:
- lib
   - image.png

Generally I acces this image using "localhost:port/package/" uri from web 

How can this be done while in a test as the port is only difine to serve test folder and not web ?

config info : Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"

Thank you

**Comment by grouma** [comment]
Hmmm. It would be trivial to do from a non-browser test. You can simply use `dart:io` with a `PackageResolver` to load the file. Is it necessary for this test to run in the browser?

An alternative which may be a little heavy handed is to use `package:build_runner`.  This package supports building, serving and testing your application through the `test` command. 

Here's an example:

`pubspec.yaml`:
```
name: sample 
version: 1.0.0 

environment:
  sdk: ">=2.0.0-dev.64.1 <3.0.0"

dev_dependencies:
  test: ^1.0.0
  build_web_compilers: any
  build_runner: any
  build_test: any
```

`test/sample_test.dart`:
```dart
import 'package:http/http.dart';
import 'package:test/test.dart';

void main() {
  test('load a lib file', () async {
    var result = await get('packages/sample/foo_data.txt');
    expect(result.body, contains('hello world'));
  });
}
```

`lib/foo_data.txt`:
```
hello world
```

Then you can run the test with `pub run build_runner test -- -p chrome`.

Otherwise you need something to serve the resource.
